"""empty message

Revision ID: 45b02c2c5375
Revises: 
Create Date: 2021-04-12 06:30:36.930944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b02c2c5375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tractortek_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_team_lead', sa.Text(), nullable=True),
    sa.Column('emp_id', sa.Text(), nullable=True),
    sa.Column('item_code', sa.Text(), nullable=True),
    sa.Column('year', sa.Text(), nullable=True),
    sa.Column('week', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tractortek_sales')
    # ### end Alembic commands ###
